name: Hello world
on: workflow_dispatch
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Build step
         run: 
           echo "Hello Step"
   test:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Test step
         run: echo "Test step" 
         
   deploy:
     runs-on: ubuntu-latest
     needs: test
     steps:
       - name: Deploy step
         run: echo "Deploy step" 
